function Hd = fdf
%FDF Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.3 and the DSP System Toolbox 8.6.
% Generated on: 28-Feb-2015 22:01:14

% Equiripple Bandpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 2;  % Sampling Frequency

Fstop1 = 0.212890625;     % First Stopband Frequency
Fpass1 = 0.271484375;     % First Passband Frequency
Fpass2 = 0.505859375;     % Second Passband Frequency
Fstop2 = 0.564453125;     % Second Stopband Frequency
Dstop1 = 0.00177827941;   % First Stopband Attenuation
Dpass  = 0.057501127785;  % Passband Ripple
Dstop2 = 0.0177827941;    % Second Stopband Attenuation
dens   = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fstop1 Fpass1 Fpass2 Fstop2]/(Fs/2), [0 1 ...
                          0], [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
